from fastapi import APIRouter

from app.api.v1.endpoints import achievements, activity, admin, alpha, analytics, auth, boss, bounty, campaign, certificate, challenges, checkout, compiler, contracts, daki, daily_anomaly, duels, evaluate, gamification, google_auth, health, hint, hotmart, incursions, intel, intercept, knowledge, leaderboard, notifications, payments, reports, sectors, session, simulate, telemetry, users

router = APIRouter(prefix="/api/v1")

router.include_router(health.router)
router.include_router(auth.router)
router.include_router(google_auth.router, tags=["google-oauth"])
router.include_router(admin.router, tags=["admin"])
router.include_router(gamification.router, prefix="/gamification", tags=["gamification"])
router.include_router(compiler.router, tags=["compiler"])
router.include_router(evaluate.router, tags=["evaluate"])
router.include_router(challenges.router, tags=["challenges"])
router.include_router(sectors.router, tags=["sectors"])
router.include_router(telemetry.router, tags=["telemetry"])
router.include_router(users.router, tags=["users"])
router.include_router(simulate.router, tags=["simulate"])
router.include_router(hint.router, tags=["hint"])
router.include_router(analytics.router, tags=["analytics"])
router.include_router(boss.router, tags=["boss"])
router.include_router(leaderboard.router, tags=["leaderboard"])
router.include_router(duels.router)
router.include_router(activity.router)
router.include_router(bounty.router)
router.include_router(certificate.router, tags=["certificate"])
router.include_router(intercept.router)
router.include_router(payments.router, tags=["payments"])
router.include_router(hotmart.router, tags=["hotmart"])
router.include_router(checkout.router, tags=["checkout"])
router.include_router(daki.router, tags=["daki"])
router.include_router(knowledge.router, tags=["knowledge"])
router.include_router(contracts.router, tags=["contracts"])
router.include_router(achievements.router)
router.include_router(session.router, tags=["session"])
router.include_router(alpha.router, tags=["alpha"])
router.include_router(intel.router)
router.include_router(incursions.router, tags=["incursions"])
router.include_router(reports.router)
router.include_router(daily_anomaly.router, tags=["daily-anomaly"])
router.include_router(campaign.router)
router.include_router(notifications.router)
